# -*- coding: utf-8 -*-
"""kivy-apk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ff8bl0bpowHi8t5q8RU3jU0ck518pgXe
"""

!pip3 install --user --upgrade buildozer

!sudo apt update

!sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

!pip3 install --user --upgrade Cython==0.29.33 virtualenv  # the --user should be removed if you do this in a venv

!/root/.local/bin/buildozer init

!/root/.local/bin/buildozer android debug